/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.alamantechnologies.secureapps.gui;

import com.alamantechnologies.secureapps.core.LockHandler;
import com.alamantechnologies.secureapps.db.DB;
import com.alamantechnologies.secureapps.util.Gen_Util;
import com.alamantechnologies.secureapps.util.JSystemFileChooser;
import com.alamantechnologies.secureapps.util.TableMouseListener;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFileChooser;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author swala
 */
public class Main_GUI extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form Main_GUI
     */
    public Main_GUI() {
        initComponents();
        setIcon();
        setLocationRelativeTo(null);
        LockHandler.getLockedAppData(lockedAppList_JTable);
        addRightMenu();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lockedAppList_JTable = new javax.swing.JTable();
        chooseApp_JButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SecureApps");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        lockedAppList_JTable.setBackground(new java.awt.Color(0, 102, 51));
        lockedAppList_JTable.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        lockedAppList_JTable.setForeground(new java.awt.Color(255, 255, 255));
        lockedAppList_JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SL.NO", "AppName", "Location", "LOCK STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lockedAppList_JTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lockedAppList_JTable.setRowHeight(30);
        jScrollPane1.setViewportView(lockedAppList_JTable);

        chooseApp_JButton.setBackground(new java.awt.Color(0, 51, 0));
        chooseApp_JButton.setForeground(new java.awt.Color(255, 255, 255));
        chooseApp_JButton.setText("Select & Lock App");
        chooseApp_JButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chooseApp_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseApp_JButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chooseApp_JButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
                        .addGap(19, 19, 19))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(chooseApp_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chooseApp_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseApp_JButtonActionPerformed
        // TODO add your handling code here:
        String filePath="";
        chooser = new JSystemFileChooser();
        chooser.setMultiSelectionEnabled(false);
        chooser.setDialogType(JFileChooser.OPEN_DIALOG);
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setDialogTitle("Select Application to Lock");
        chooser.setApproveButtonText("Lock App");
        int i=chooser.showDialog(rootPane, null);
        if(i==0)
        {
            filePath=String.valueOf(chooser.getSelectedFile().getAbsoluteFile());
            if(db.checkRecord("LOCKED_APPS_TBL", "APP_LOCATION='"+filePath+"'"))
            {
                Gen_Util.showInformationDialog(rootPane, "App already exists in list!");
                
            }
            else
            {
                if(LockHandler.lockApp(filePath))
                {
                    Gen_Util.showSuccessDialog(rootPane, "Successfully Locked!");
                }
        
                LockHandler.getLockedAppData(lockedAppList_JTable);
                
            }
        }
        
    }//GEN-LAST:event_chooseApp_JButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseApp_JButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lockedAppList_JTable;
    // End of variables declaration//GEN-END:variables
    DB db = new DB();
    private JSystemFileChooser chooser;
    private JPopupMenu popupMenu;
    private JMenuItem menuItem_Lock;
    private JMenuItem menuItem_UnLock;
    private DefaultTableModel tModel;
    private void addRightMenu()
    {
        tModel = (DefaultTableModel) lockedAppList_JTable.getModel();
        
        popupMenu = new JPopupMenu();
        menuItem_UnLock = new JMenuItem("UnLock");
        menuItem_UnLock.addActionListener(this);
        popupMenu.add(menuItem_UnLock);
        
        menuItem_Lock = new JMenuItem("Lock");
        menuItem_Lock.addActionListener(this);
        popupMenu.add(menuItem_Lock);
        
        lockedAppList_JTable.setComponentPopupMenu(popupMenu);
        lockedAppList_JTable.addMouseListener(new TableMouseListener(lockedAppList_JTable));
        
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        int row;
        
        JMenuItem menu = (JMenuItem) e.getSource();
        
        if(menu == menuItem_UnLock)
        {
            row = lockedAppList_JTable.getSelectedRow();
            String fileLocation = "";
            String encKey = "";

            fileLocation = String.valueOf(lockedAppList_JTable.getValueAt(row, 2));
            if(LockHandler.unLockApp(fileLocation))
            {
                Gen_Util.showSuccessDialog(rootPane, "Successfully UnLocked!");
            }
            LockHandler.getLockedAppData(lockedAppList_JTable);
        }
        if(menu == menuItem_Lock)
        {
            row = lockedAppList_JTable.getSelectedRow();
            String fileLocation = "";
            String encKey = "";

            fileLocation = String.valueOf(lockedAppList_JTable.getValueAt(row, 2));
            if(LockHandler.lockApp(fileLocation))
            {
                Gen_Util.showSuccessDialog(rootPane, "Successfully Locked!");
            }
        
            LockHandler.getLockedAppData(lockedAppList_JTable);
        }
    }
    
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/com/alamantechnologies/secureapps/img/icon.jpg")));
        
    }
}
